<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <PackageId>MakeItEasyCQRS</PackageId>
    <Version>1.0.3</Version>
    <Authors>João Greco</Authors>
    <Company>grecojoao</Company>
    <PackageDescription>Easily use the CQRS design pattern!</PackageDescription>
    <RepositoryUrl>https://github.com/grecojoao/MakeItEasyCQRS</RepositoryUrl>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <AssemblyVersion>1.0.0.3</AssemblyVersion>
    <FileVersion>1.0.0.3</FileVersion>
    <Description />
    <PackageReleaseNotes>Added .NET 8 and .NET 10 support.</PackageReleaseNotes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DomainNotifications" Version="1.0.2" />
  </ItemGroup>

</Project>
